default:
  interruptible: false
  image: node:latest

stages:          # List of stages for jobs, and their order of execution
  - build-deploy

build-deploy-app:       # This job runs in the build stage, which runs first.
  stage: build-deploy
  only:
    - main
  script:
    - yarn cache clean && yarn && du -d1 -h $(yarn cache dir)
    - yarn global add vercel
    - vercel pull --yes --token=$VERCEL_TOKEN
    - vercel --prod --prebuilt --token=$VERCEL_TOKEN 
  tags:
    - CMS